// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/15/2025, 1:15:00 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/ibidi/Desktop/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ibidi/Desktop/website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ibidi/Desktop/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ibidi/Desktop/website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ibidi/Desktop/website/plugins/**/*.{js,ts,mjs}","/Users/ibidi/Desktop/website/composables/**/*.{js,ts,mjs}","/Users/ibidi/Desktop/website/utils/**/*.{js,ts,mjs}","/Users/ibidi/Desktop/website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ibidi/Desktop/website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ibidi/Desktop/website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["16"] = "/Users/ibidi/Desktop/website/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;